# -*- coding: utf-8 -*-
"""Lab4_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nv9Tf8ctLRiux_RUhl7izcKYRXQfQ84T
"""

# Q2 part1

import os

def srch(d):
  for item in os.listdir(d):
    path = os.path.join(d,item)
    if os.path.isfile(path):
      if path[-3:] == "mp3":
        print(path)
    else:
      srch(path)

srch("/content")

# Q2 Part 2
import hashlib
import os

def srch(d):
  for item in os.listdir(d):
    path = os.path.join(d,item)
    if os.path.isfile(path):
      if path[-3:] == "mp3":
        print(path , hashlib.md5(open(path,"rb").read()))
    else:
      srch(path)

srch("/content")