# -*- coding: utf-8 -*-
"""Lab4_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nv9Tf8ctLRiux_RUhl7izcKYRXQfQ84T
"""

#LAB4 Q2

import os

def chk(dirname, file):
  for file_name in os.listdir(directory_name):
    paths = os.path.join(directory_name,file_name)
    if os.path.isfile(paths):
      print(paths)
    else:
      chk(dirname, file)